# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_shrinkDSM <- function(y, z, mod_type, delta, it, group, niter, nburn, nthin, d1, d2, e1, e2, sigma2_phi, learn_lambda2_B, learn_kappa2_B, lambda2_B, kappa2_B, learn_a_xi, learn_a_tau, a_xi, a_tau, learn_c_xi, learn_c_tau, c_xi, c_tau, a_eq_c_xi, a_eq_c_tau, a_tuning_par_xi, a_tuning_par_tau, c_tuning_par_xi, c_tuning_par_tau, beta_a_xi, beta_a_tau, alpha_a_xi, alpha_a_tau, beta_c_xi, beta_c_tau, alpha_c_xi, alpha_c_tau, Bsigma_sv, a0_sv, b0_sv, display_progress, adaptive, target_rates, max_adapts, batch_sizes, tv_inputs, phi_prior) {
    .Call(`_shrinkDSM_do_shrinkDSM`, y, z, mod_type, delta, it, group, niter, nburn, nthin, d1, d2, e1, e2, sigma2_phi, learn_lambda2_B, learn_kappa2_B, lambda2_B, kappa2_B, learn_a_xi, learn_a_tau, a_xi, a_tau, learn_c_xi, learn_c_tau, c_xi, c_tau, a_eq_c_xi, a_eq_c_tau, a_tuning_par_xi, a_tuning_par_tau, c_tuning_par_xi, c_tuning_par_tau, beta_a_xi, beta_a_tau, alpha_a_xi, alpha_a_tau, beta_c_xi, beta_c_tau, alpha_c_xi, alpha_c_tau, Bsigma_sv, a0_sv, b0_sv, display_progress, adaptive, target_rates, max_adapts, batch_sizes, tv_inputs, phi_prior)
}

init_export <- function(it, y, delta, G, Z, Z_tau, grouped, tv_inputs) {
    .Call(`_shrinkDSM_init_export`, it, y, delta, G, Z, Z_tau, grouped, tv_inputs)
}

